# Generated by Django 3.2.7 on 2021-09-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('day', models.DateTimeField()),
                ('reminder', models.BooleanField(default=True)),
            ],
        ),
    ]
