# Generated by Django 3.2.7 on 2021-09-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.DateField(),
        ),
    ]
